name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t le-ssl-rancher .
#       - name: Tags
#         run: |
#           docker tag le-ssl-rancher ${{ secrets.DOCKER_USER }}/le-ssl-rancher:${{ github.sha }}
#           docker tag le-ssl-rancher ${{ secrets.DOCKER_USER }}/le-ssl-rancher:latest
#       - name: Push
#         run: |
#           docker push ${{ secrets.DOCKER_USER }}/le-ssl-rancher:${{ github.sha }}
#           docker push ${{ secrets.DOCKER_USER }}/le-ssl-rancher:latest
